apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpZdwpNVFU0TkRSYUZ3MDBNekF4TWpZd01UVTRORFJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDZDdTYnlrV2wwTm94dC96UFZ4RzFIdWZYQVQzSm8wOHJkaWdJanpMWUNYd25oTEpadApib25Va3hjTUdOMzRuL0hJWnhTc3ovVVpRVSttSkpQcmIrY2NnSFhlT3dteU5ob3FmZFF2R1ZCWWVEZFpQUDl3CklDWkNDY1JBQy9SZ1IyR3JEb1N0QVFtSm5BWHFvNk80VnpkOElLWmY5QnZsM1JiM1pjenFMUWZLY0R3ZVRBRU8KaVhiVEZ1MGdBTVV1eVhneGtpZld2eDJ0b0ZqbEVpcUZVenJ1bEt1M056MUZ6SytuNHlVYUlGVm04eFUzVUtBOApxbWdtOVlQVTBpTEJiaFEyZ3VZL3dQOVdPTUdIeHdRSmxsdVRKUnFSU3U2ZmxiWS9YTk1XdjFscG5DUWtiWDg3Clo3NGVWRzJka1llRUpMQ3Y0bUs4SEwyNE9XUHVPbm0vWldJUEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlQ3N2IvbDFQb0VobE9hSU1tYwpYTzdCbCt2bjJqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFEeG9UMEN3NWt4WGNVOGlYNFd5MHNxc294dHFGCjdhY3FDa1pKb0M0Q2ozNjJsOWJzbXJqck1tTlUxODJDV3M5QzdCaTF4U0lEaExDSXBVemRqN1lYN0lCNXFmZ0EKem5FMDJzcXVtblo5SHF5MmNraFY4Y1FvbUNhcWR1dFFuYmsyLzIwWW50aDNpMGtldXZyUWQ3aVRpMWZjUlgydAoydGczbkU1OFNDNTlCaVU1b2pUazlUOGIvY0VvMVEzU2s1aUgwcDBCekxmL3pKUjA5K3MyTEJoT0hpRmRUdjltCkJLc1l5eldlcjNVaDk1ZFlRTXhZa2RVc201Y1RQQmdyV1Vwc3JQZG5iUCtJZlBJSG4wOWdrRWR6L2dHc2R0eGIKcVJjcUIxcEZWRWwrb01lY09TbDZCOGwyT3BiZW51bVRHMkI4THZmdnhCcEQ1UlUxSHIzakF6OFJCdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://24d7f2f1-6d0e-46e0-a689-1a3e9e79ec85.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_d882701a628cac422389f1a6962d1d4b3fcba656ac6cd905c33834e9ed196b3a
